### ISSUE TITLE
The code of Supercollider and Foxdot?

### ISSUE THREAD

**Issue by Catsvilles** [open-source-grilled-cheese/lofi-fy#1]
Hey guys, just read through your submission and watched the video and wanted to check out how exactly you managed to make all this works, specifically "getting foxdot to output a file", did you use NRT or something? Because from what I know it's not so easy with Foxdot. Is there a chance to look at how you solved this problem? 
Also, [lofi-fy.space](lofi-fy.space) is down, and not possible to try it out :(

**Comment by centipeda** [comment]
Yep, you're right, it's a pain to get Foxdot to output a file normally. We found this shell script that uses jackd and xvfb to set up and tear down Foxdot so it can stream to a file instead of to the audio stream: https://github.com/ekg/foxsamply

You actually caught us right as I was migrating lofi-fy to another server... it should be up in a little while, so you can try it out.

**Comment by Catsvilles** [comment]
@centipeda thanks for the reply! Do I understand right that it records in real-time, thus we have to wait for the file to play to get the specified duration? Would be cool to find a way to do it offline though, too bad Foxdot doesn't allow converting it's patterns to list of OSC messages. At least from what I understand.

Ah, okay, will check it out when it's online! :)

**Comment by centipeda** [comment]
Yes, exactly, it records in real time. I think it might be possible to hook into FoxDot itself and record the OSC messages that it's sending to SuperCollider (either that or see if the SuperCollider server itself keeps the messages it receives), which would be a cleaner solution. We thought it would be possible to let SuperCollider record stuff statically, but we couldn't figure it out in time.

Unfortunately the nature of a hackathon meant we went with the first available solution that worked, which turned out to be just letting FoxDot record live.
